-- ============================================================================
-- Sistema de Tours de Agencias de Viajes Salvadoreñas - Grupo 4
-- PDM115 - Ciclo I 2026 - ETAPA 2
-- Estructura de tablas MySQL (espejo del esquema SQLite de la app Android)
-- ============================================================================

CREATE DATABASE IF NOT EXISTS tours_gpo4
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tours_gpo4;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ACCESO_USUARIO;
DROP TABLE IF EXISTS OPCION_CRUD;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS DETALLE_FACTURA;
DROP TABLE IF EXISTS VACUNA_TURISTA;
DROP TABLE IF EXISTS DOCUMENTO_TURISTA;
DROP TABLE IF EXISTS REQUISITO_VACUNA_DESTINO;
DROP TABLE IF EXISTS PRECIO_PAQUETE_CLASE;
DROP TABLE IF EXISTS PAQUETE_MOTIVACION;
DROP TABLE IF EXISTS PAQUETE_DESTINO;
DROP TABLE IF EXISTS DESTINO_MOTIVACION;
DROP TABLE IF EXISTS INSCRIPCION;
DROP TABLE IF EXISTS FACTURA;
DROP TABLE IF EXISTS PAQUETE_TURISTICO;
DROP TABLE IF EXISTS TURISTA;
DROP TABLE IF EXISTS DESTINO;
DROP TABLE IF EXISTS VACUNA;
DROP TABLE IF EXISTS FORMA_PAGO;
DROP TABLE IF EXISTS TIPO_AGRUPACION;
DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS ENFERMEDAD;
DROP TABLE IF EXISTS MOTIVACIONES;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS CLASE_PASAJERO;
DROP TABLE IF EXISTS AGENCIA_VIAJE;

SET FOREIGN_KEY_CHECKS = 1;

-- ---- 1) CATÁLOGOS ----
CREATE TABLE AGENCIA_VIAJE (
    IDAGENCIA     VARCHAR(10)  NOT NULL,
    NOMBREAGENCIA VARCHAR(80)  NOT NULL,
    DIRECCION     VARCHAR(150) NOT NULL,
    TELEFONO      VARCHAR(20)  NOT NULL,
    CORREO        VARCHAR(80)  NOT NULL,
    PRIMARY KEY (IDAGENCIA)
) ENGINE=InnoDB;

CREATE TABLE CLASE_PASAJERO (
    IDCLASE     VARCHAR(10) NOT NULL,
    NOMBRECLASE VARCHAR(40) NOT NULL,
    PRIMARY KEY (IDCLASE)
) ENGINE=InnoDB;

CREATE TABLE PAIS (
    IDPAIS     VARCHAR(10) NOT NULL,
    NOMBREPAIS VARCHAR(60) NOT NULL,
    PRIMARY KEY (IDPAIS)
) ENGINE=InnoDB;

CREATE TABLE MOTIVACIONES (
    IDMOTIVACION  VARCHAR(10) NOT NULL,
    DESMOTIVACION VARCHAR(60) NOT NULL,
    PRIMARY KEY (IDMOTIVACION)
) ENGINE=InnoDB;

CREATE TABLE ENFERMEDAD (
    IDENFERMEDAD     VARCHAR(10) NOT NULL,
    NOMBREENFERMEDAD VARCHAR(60) NOT NULL,
    PRIMARY KEY (IDENFERMEDAD)
) ENGINE=InnoDB;

CREATE TABLE TIPO_DOCUMENTO (
    IDTIPODOC       VARCHAR(10)  NOT NULL,
    DESTIPODOC      VARCHAR(40)  NOT NULL,
    LONGITUDMIN     INT          NOT NULL,
    LONGITUDMAX     INT          NOT NULL,
    REGEXVALIDACION VARCHAR(80)  NOT NULL,
    FORMATOEJEMPLO  VARCHAR(40),
    MENSAJEERROR    VARCHAR(120) NOT NULL,
    ACTIVO          INT          NOT NULL DEFAULT 1,
    PRIMARY KEY (IDTIPODOC)
) ENGINE=InnoDB;

CREATE TABLE TIPO_AGRUPACION (
    IDTIPOAGRUP  VARCHAR(10) NOT NULL,
    DESTIPOAGRUP VARCHAR(40) NOT NULL,
    PRIMARY KEY (IDTIPOAGRUP)
) ENGINE=InnoDB;

CREATE TABLE FORMA_PAGO (
    IDFORMAPAGO  VARCHAR(10) NOT NULL,
    DESFORMAPAGO VARCHAR(40) NOT NULL,
    PRIMARY KEY (IDFORMAPAGO)
) ENGINE=InnoDB;

-- ---- 2) TABLAS PRINCIPALES ----
CREATE TABLE VACUNA (
    IDVACUNA     VARCHAR(10) NOT NULL,
    IDENFERMEDAD VARCHAR(10),
    NOMBREVACUNA VARCHAR(80) NOT NULL,
    PRIMARY KEY (IDVACUNA),
    CONSTRAINT FK_VACUNA_ENFERMEDAD FOREIGN KEY (IDENFERMEDAD) REFERENCES ENFERMEDAD(IDENFERMEDAD)
) ENGINE=InnoDB;

CREATE TABLE DESTINO (
    IDDESTINO       VARCHAR(10)  NOT NULL,
    IDPAIS          VARCHAR(10),
    NOMBREDESTINO   VARCHAR(80)  NOT NULL,
    DESDESTINO      VARCHAR(200) NOT NULL,
    REQUIEREVISAESP INT          NOT NULL,
    PRIMARY KEY (IDDESTINO),
    CONSTRAINT FK_DESTINO_PAIS FOREIGN KEY (IDPAIS) REFERENCES PAIS(IDPAIS)
) ENGINE=InnoDB;

CREATE TABLE TURISTA (
    IDTURISTA       VARCHAR(10) NOT NULL,
    IDPAIS          VARCHAR(10),
    NOMBRES         VARCHAR(60) NOT NULL,
    APELLIDOS       VARCHAR(60) NOT NULL,
    FECHANACIMIENTO VARCHAR(10) NOT NULL,
    TELEFONO        VARCHAR(20),
    CORREO          VARCHAR(80),
    TIENEVISA       INT         NOT NULL,
    PRIMARY KEY (IDTURISTA),
    CONSTRAINT FK_TURISTA_PAIS FOREIGN KEY (IDPAIS) REFERENCES PAIS(IDPAIS)
) ENGINE=InnoDB;

CREATE TABLE PAQUETE_TURISTICO (
    IDPAQUETE     VARCHAR(10)  NOT NULL,
    IDAGENCIA     VARCHAR(10),
    NOMBREPAQUETE VARCHAR(80)  NOT NULL,
    DESPAQUETE    VARCHAR(200) NOT NULL,
    FECHAINICIO   VARCHAR(10)  NOT NULL,
    FECHAFIN      VARCHAR(10)  NOT NULL,
    CUPOMAXIMO    INT          NOT NULL,
    ESTADO        VARCHAR(20),
    PRIMARY KEY (IDPAQUETE),
    CONSTRAINT FK_PAQUETE_AGENCIA FOREIGN KEY (IDAGENCIA) REFERENCES AGENCIA_VIAJE(IDAGENCIA)
) ENGINE=InnoDB;

CREATE TABLE FACTURA (
    IDFACTURA    VARCHAR(10)   NOT NULL,
    IDTIPOAGRUP  VARCHAR(10),
    IDFORMAPAGO  VARCHAR(10),
    FECHAEMISION VARCHAR(10)   NOT NULL,
    NOMBREGRUPO  VARCHAR(80)   NOT NULL,
    TOTAL        DECIMAL(10,2) NOT NULL,
    ESTADO       VARCHAR(20)   NOT NULL,
    PRIMARY KEY (IDFACTURA),
    CONSTRAINT FK_FACTURA_TIPOAGRUP FOREIGN KEY (IDTIPOAGRUP) REFERENCES TIPO_AGRUPACION(IDTIPOAGRUP),
    CONSTRAINT FK_FACTURA_FORMAPAGO FOREIGN KEY (IDFORMAPAGO) REFERENCES FORMA_PAGO(IDFORMAPAGO)
) ENGINE=InnoDB;

CREATE TABLE INSCRIPCION (
    IDINSCRIPCION    VARCHAR(10) NOT NULL,
    IDPAQUETE        VARCHAR(10),
    IDCLASE          VARCHAR(10),
    IDTURISTA        VARCHAR(10),
    FECHAINSCRIPCION VARCHAR(10) NOT NULL,
    ESTADO           VARCHAR(20) NOT NULL,
    PRIMARY KEY (IDINSCRIPCION),
    CONSTRAINT FK_INSC_PAQUETE FOREIGN KEY (IDPAQUETE) REFERENCES PAQUETE_TURISTICO(IDPAQUETE),
    CONSTRAINT FK_INSC_CLASE   FOREIGN KEY (IDCLASE)   REFERENCES CLASE_PASAJERO(IDCLASE),
    CONSTRAINT FK_INSC_TURISTA FOREIGN KEY (IDTURISTA) REFERENCES TURISTA(IDTURISTA)
) ENGINE=InnoDB;

-- ---- 3) TABLAS INTERMEDIAS M:N Y DETALLE ----
CREATE TABLE DESTINO_MOTIVACION (
    IDMOTIVACION VARCHAR(10) NOT NULL,
    IDDESTINO    VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDMOTIVACION, IDDESTINO),
    CONSTRAINT FK_DM_MOTIVACION FOREIGN KEY (IDMOTIVACION) REFERENCES MOTIVACIONES(IDMOTIVACION),
    CONSTRAINT FK_DM_DESTINO    FOREIGN KEY (IDDESTINO)    REFERENCES DESTINO(IDDESTINO)
) ENGINE=InnoDB;

CREATE TABLE PAQUETE_DESTINO (
    IDPAQUETE VARCHAR(10) NOT NULL,
    IDDESTINO VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDPAQUETE, IDDESTINO),
    CONSTRAINT FK_PD_PAQUETE FOREIGN KEY (IDPAQUETE) REFERENCES PAQUETE_TURISTICO(IDPAQUETE),
    CONSTRAINT FK_PD_DESTINO FOREIGN KEY (IDDESTINO) REFERENCES DESTINO(IDDESTINO)
) ENGINE=InnoDB;

CREATE TABLE PAQUETE_MOTIVACION (
    IDMOTIVACION VARCHAR(10) NOT NULL,
    IDPAQUETE    VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDMOTIVACION, IDPAQUETE),
    CONSTRAINT FK_PM_MOTIVACION FOREIGN KEY (IDMOTIVACION) REFERENCES MOTIVACIONES(IDMOTIVACION),
    CONSTRAINT FK_PM_PAQUETE    FOREIGN KEY (IDPAQUETE)    REFERENCES PAQUETE_TURISTICO(IDPAQUETE)
) ENGINE=InnoDB;

CREATE TABLE PRECIO_PAQUETE_CLASE (
    IDPAQUETE      VARCHAR(10)   NOT NULL,
    IDCLASE        VARCHAR(10)   NOT NULL,
    PRECIO_PAQUETE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (IDPAQUETE, IDCLASE),
    CONSTRAINT FK_PPC_PAQUETE FOREIGN KEY (IDPAQUETE) REFERENCES PAQUETE_TURISTICO(IDPAQUETE),
    CONSTRAINT FK_PPC_CLASE   FOREIGN KEY (IDCLASE)   REFERENCES CLASE_PASAJERO(IDCLASE)
) ENGINE=InnoDB;

CREATE TABLE REQUISITO_VACUNA_DESTINO (
    IDDESTINO VARCHAR(10) NOT NULL,
    IDVACUNA  VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDDESTINO, IDVACUNA),
    CONSTRAINT FK_RVD_DESTINO FOREIGN KEY (IDDESTINO) REFERENCES DESTINO(IDDESTINO),
    CONSTRAINT FK_RVD_VACUNA  FOREIGN KEY (IDVACUNA)  REFERENCES VACUNA(IDVACUNA)
) ENGINE=InnoDB;

CREATE TABLE DOCUMENTO_TURISTA (
    IDTURISTA VARCHAR(10) NOT NULL,
    IDTIPODOC VARCHAR(10) NOT NULL,
    NUM_DOC   VARCHAR(20) NOT NULL,
    PRIMARY KEY (IDTURISTA, IDTIPODOC),
    CONSTRAINT FK_DOC_TURISTA FOREIGN KEY (IDTURISTA) REFERENCES TURISTA(IDTURISTA),
    CONSTRAINT FK_DOC_TIPODOC FOREIGN KEY (IDTIPODOC) REFERENCES TIPO_DOCUMENTO(IDTIPODOC)
) ENGINE=InnoDB;

CREATE TABLE VACUNA_TURISTA (
    IDTURISTA       VARCHAR(10) NOT NULL,
    IDVACUNA        VARCHAR(10) NOT NULL,
    FECHAAPLICACION VARCHAR(10) NOT NULL,
    FECHAVIGENCIA   VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDTURISTA, IDVACUNA),
    CONSTRAINT FK_VT_TURISTA FOREIGN KEY (IDTURISTA) REFERENCES TURISTA(IDTURISTA),
    CONSTRAINT FK_VT_VACUNA  FOREIGN KEY (IDVACUNA)  REFERENCES VACUNA(IDVACUNA)
) ENGINE=InnoDB;

CREATE TABLE DETALLE_FACTURA (
    IDFACTURA      VARCHAR(10)   NOT NULL,
    IDINSCRIPCION  VARCHAR(10)   NOT NULL,
    PRECIOUNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL       DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (IDFACTURA, IDINSCRIPCION),
    CONSTRAINT FK_DF_FACTURA     FOREIGN KEY (IDFACTURA)     REFERENCES FACTURA(IDFACTURA),
    CONSTRAINT FK_DF_INSCRIPCION FOREIGN KEY (IDINSCRIPCION) REFERENCES INSCRIPCION(IDINSCRIPCION)
) ENGINE=InnoDB;

-- ---- 4) CONTROL DE ACCESO ----
CREATE TABLE USUARIO (
    IDUSUARIO  VARCHAR(10)  NOT NULL,
    NOMUSUARIO VARCHAR(40)  NOT NULL UNIQUE,
    CLAVE      VARCHAR(100) NOT NULL,
    ROL        VARCHAR(20)  NOT NULL,
    ACTIVO     INT          NOT NULL DEFAULT 1,
    PRIMARY KEY (IDUSUARIO)
) ENGINE=InnoDB;

CREATE TABLE OPCION_CRUD (
    IDOPCION  VARCHAR(10) NOT NULL,
    DESOPCION VARCHAR(60) NOT NULL,
    NUMCRUD   INT         NOT NULL,
    PRIMARY KEY (IDOPCION)
) ENGINE=InnoDB;

CREATE TABLE ACCESO_USUARIO (
    IDUSUARIO VARCHAR(10) NOT NULL,
    IDOPCION  VARCHAR(10) NOT NULL,
    PRIMARY KEY (IDUSUARIO, IDOPCION),
    CONSTRAINT FK_AU_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_AU_OPCION  FOREIGN KEY (IDOPCION)  REFERENCES OPCION_CRUD(IDOPCION)
) ENGINE=InnoDB;